/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#910807",
        "primary-fixed-dim": "#48e08f",
        "surface": "#111417",
        "inverse-on-surface": "#2e3134",
        "on-primary-fixed": "#00210f",
        "secondary-fixed-dim": "#92ccff",
        "surface-container-highest": "#323538",
        "on-background": "#e1e2e6",
        "secondary-fixed": "#cce5ff",
        "on-surface": "#e1e2e6",
        "on-tertiary-container": "#960e09",
        "surface-variant": "#323538",
        "error": "#ffb4ab",
        "surface-container-low": "#191c1f",
        "primary": "#5af09d",
        "on-error-container": "#ffdad6",
        "on-primary": "#00391e",
        "on-secondary": "#003351",
        "surface-tint": "#48e08f",
        "on-primary-container": "#005630",
        "surface-container-high": "#272a2d",
        "primary-fixed": "#69fda8",
        "surface-container-lowest": "#0b0f11",
        "on-secondary-container": "#002c47",
        "background": "#111417",
        "on-tertiary": "#690001",
        "on-secondary-fixed-variant": "#004b73",
        "tertiary": "#ffc9c1",
        "tertiary-fixed": "#ffdad5",
        "inverse-primary": "#006d3e",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#00522d",
        "tertiary-container": "#ffa194",
        "tertiary-fixed-dim": "#ffb4a9",
        "outline-variant": "#3c4a3f",
        "surface-container": "#1d2023",
        "on-secondary-fixed": "#001d31",
        "secondary": "#92ccff",
        "surface-bright": "#37393d",
        "on-surface-variant": "#bbcabc",
        "inverse-surface": "#e1e2e6",
        "on-tertiary-fixed": "#410000",
        "outline": "#869488",
        "primary-container": "#36d383",
        "surface-dim": "#111417",
        "secondary-container": "#3398db",
        "on-error": "#690005",
        // Legacy colors in case they are referenced
        'bio-bg': '#111417',
        'bio-card': '#1D2023',
        'bio-border': '#3C4A3F',
        'bio-green': '#5AF09D',
        'bio-muted': '#869488',
        'bio-red': '#FFA194',
        'bio-blue': '#92CCFF',
        'bio-gold': '#FFDAD5',
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "touch-target-min": "44px",
        "stack-lg": "24px",
        "margin-desktop": "32px",
        "gutter": "16px",
        "base": "8px",
        "stack-sm": "4px",
        "stack-md": "12px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "mono-data": ["Inter", "monospace"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "mono-data": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
